namespace OOT_AP_Client.Enums;

public enum Area
{
	// Overworld
	KokiriForest,
	LostWoods,
	SacredForestMeadow,
	HyruleField,
	LonLonRanch,
	Market,
	HyruleCastle,
	KakarikoVillage,
	Graveyard,
	DeathMountainTrail,
	GoronCity,
	DeathMountainCrater,
	ZorasRiver,
	ZorasDomain,
	ZorasFountain,
	LakeHylia,
	GerudoValley,
	GerudoFortress,
	HauntedWasteland,
	DesertColossus,
	OutsideGanonsCastle,

	// Dungeons
	DekuTree,
	DekuTreeMQ,
	DodongosCavern,
	DodongosCavernMQ,
	JabuJabusBelly,
	JabuJabusBellyMQ,
	ForestTemple,
	ForestTempleMQ,
	FireTemple,
	FireTempleMQ,
	IceCavern,
	IceCavernMQ,
	WaterTemple,
	WaterTempleMQ,
	BottomOfTheWell,
	BottomOfTheWellMQ,
	ShadowTemple,
	ShadowTempleMQ,
	GerudoTrainingGround,
	GerudoTrainingGroundMQ,
	SpiritTemple,
	SpiritTempleMQ,
	GanonsCastle,
	GanonsCastleMQ,
}
